# Generated by Django 4.0.2 on 2022-02-19 03:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('describe', ckeditor.fields.RichTextField()),
                ('isComplete', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
