# Generated by Django 4.0.2 on 2022-02-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_achievment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievment',
            name='Readable',
            field=models.BooleanField(default=True),
        ),
    ]
