# Generated by Django 4.0.2 on 2022-02-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_achievment_readable'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievment',
            name='liveUrl',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='achievment',
            name='sourceUrl',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
