# Generated by Django 4.0.2 on 2022-02-19 08:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_achievment_liveurl_achievment_sourceurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='describe',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
