# Generated by Django 4.0.2 on 2022-02-21 03:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_achievment_thumnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='describe',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
