# Generated by Django 4.0.2 on 2022-02-21 04:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_achievment_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='describe',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
